### ISSUE TITLE
Does it not work with go 1.11?

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/autograph#185]
Tried this:

```bash
▶ go version
go version go1.11.2 darwin/amd64

▶ go get go.mozilla.org/autograph
# go.mozilla.org/autograph/vendor/github.com/miekg/pkcs11
In file included from ../../../GO/src/go.mozilla.org/autograph/vendor/github.com/miekg/pkcs11/pkcs11.go:28:
/usr/local/include/ltdl.h:36:10: fatal error: 'libltdl/lt_system.h' file not found
#include <libltdl/lt_system.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

I'm not sure what https://github.com/mozilla-services/autograph/issues/152 means but perhaps it means "Make autograph work in go 1.11". 

The [Dockerfile](https://github.com/mozilla-services/autograph/blob/master/Dockerfile#L1) uses go 1.10. 

If you can't use go 1.11 with this project, then this issue isn't a question but a task to update the README mention this.

**Comment by jvehent** [comment]
This is because you're missing libtool-ltdl-devel. I'll update the docs.

**Comment by g-k** [comment]
@peterbe can you try `brew install libtool` and let us know if that fixes the problem?

I'll try this from my mac when I'm back home too.

**Comment by peterbe** [comment]
Homebrew said this:

```
Warning: libtool 2.4.6_1 is already installed and up-to-date
To reinstall 2.4.6_1, run `brew reinstall libtool`
```

**Comment by g-k** [comment]
OK weird. It seems to install for me. I have:

```console
$ go version
go version go1.11 darwin/amd64
$ brew install libtool
Warning: libtool 2.4.6_1 is already installed and up-to-date
To reinstall 2.4.6_1, run `brew reinstall libtool`
$ go get -u go.mozilla.org/autograph
# go.mozilla.org/autograph
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
$ 
```

I don't have ltdl in my history though. Do you have the following symlinks?

```
$ ls -lh /usr/local/include/ltdl.h
lrwxr-xr-x  1 greg  staff    40B Aug  1  2016 /usr/local/include/ltdl.h -> ../Cellar/libtool/2.4.6_1/include/ltdl.h
$ ls -lh /usr/local/lib/libltdl.*                                                                                                                   
lrwxr-xr-x  1 greg  staff    45B Aug  1  2016 /usr/local/lib/libltdl.7.dylib -> ../Cellar/libtool/2.4.6_1/lib/libltdl.7.dylib
lrwxr-xr-x  1 greg  staff    39B Aug  1  2016 /usr/local/lib/libltdl.a -> ../Cellar/libtool/2.4.6_1/lib/libltdl.a
lrwxr-xr-x  1 greg  staff    43B Aug  1  2016 /usr/local/lib/libltdl.dylib -> ../Cellar/libtool/2.4.6_1/lib/libltdl.dylib
```

**Comment by g-k** [comment]
oh we might need to `brew link libtool` too

**Comment by g-k** [comment]
an unlink then link adds:

```console
brew link -v libtool                                                                                                                               master 
Linking /usr/local/Cellar/libtool/2.4.6_1... 
ln -s ../Cellar/libtool/2.4.6_1/bin/glibtool glibtool
ln -s ../Cellar/libtool/2.4.6_1/bin/glibtoolize glibtoolize
ln -s ../Cellar/libtool/2.4.6_1/include/libltdl libltdl
ln -s ../Cellar/libtool/2.4.6_1/include/ltdl.h ltdl.h
ln -s ../../Cellar/libtool/2.4.6_1/share/aclocal/libtool.m4 libtool.m4
ln -s ../../Cellar/libtool/2.4.6_1/share/aclocal/ltargz.m4 ltargz.m4
ln -s ../../Cellar/libtool/2.4.6_1/share/aclocal/ltdl.m4 ltdl.m4
ln -s ../../Cellar/libtool/2.4.6_1/share/aclocal/ltoptions.m4 ltoptions.m4
ln -s ../../Cellar/libtool/2.4.6_1/share/aclocal/ltsugar.m4 ltsugar.m4
ln -s ../../Cellar/libtool/2.4.6_1/share/aclocal/ltversion.m4 ltversion.m4
ln -s ../../Cellar/libtool/2.4.6_1/share/aclocal/lt~obsolete.m4 lt~obsolete.m4
ln -s ../../Cellar/libtool/2.4.6_1/share/info/libtool.info libtool.info
info /usr/local/share/info/libtool.info
ln -s ../../Cellar/libtool/2.4.6_1/share/info/libtool.info-1 libtool.info-1
ln -s ../../Cellar/libtool/2.4.6_1/share/info/libtool.info-2 libtool.info-2
ln -s ../Cellar/libtool/2.4.6_1/share/libtool libtool
ln -s ../../../Cellar/libtool/2.4.6_1/share/man/man1/glibtool.1 glibtool.1
ln -s ../../../Cellar/libtool/2.4.6_1/share/man/man1/glibtoolize.1 glibtoolize.1
ln -s ../Cellar/libtool/2.4.6_1/lib/libltdl.7.dylib libltdl.7.dylib
ln -s ../Cellar/libtool/2.4.6_1/lib/libltdl.a libltdl.a
ln -s ../Cellar/libtool/2.4.6_1/lib/libltdl.dylib libltdl.dylib
20 symlinks created
```

**Comment by jvehent** [comment]
@peterbe could you grab the latest master and give it another try?

**Comment by peterbe** [comment]
It seems, unlinking and linking solved the problem. See:


```
▶ brew unlink -v libtool
Unlinking /usr/local/Cellar/libtool/2.4.6_1...
rm /usr/local/bin/glibtool
rm /usr/local/bin/glibtoolize
rm /usr/local/include/ltdl.h
rm /usr/local/lib/libltdl.7.dylib
rm /usr/local/lib/libltdl.a
rm /usr/local/lib/libltdl.dylib
rm /usr/local/share/aclocal/libtool.m4
rm /usr/local/share/aclocal/ltargz.m4
rm /usr/local/share/aclocal/ltdl.m4
rm /usr/local/share/aclocal/ltoptions.m4
rm /usr/local/share/aclocal/ltsugar.m4
rm /usr/local/share/aclocal/ltversion.m4
rm /usr/local/share/aclocal/lt~obsolete.m4
uninfo /usr/local/share/info/libtool.info
rm /usr/local/share/info/libtool.info
rm /usr/local/share/info/libtool.info-1
rm /usr/local/share/info/libtool.info-2
rm /usr/local/share/man/man1/glibtool.1
rm /usr/local/share/man/man1/glibtoolize.1
18 symlinks removed

~
▶ brew link -v libtool
Linking /usr/local/Cellar/libtool/2.4.6_1...
ln -s ../Cellar/libtool/2.4.6_1/bin/glibtool glibtool
ln -s ../Cellar/libtool/2.4.6_1/bin/glibtoolize glibtoolize
ln -s ../Cellar/libtool/2.4.6_1/include/libltdl libltdl
ln -s ../Cellar/libtool/2.4.6_1/include/ltdl.h ltdl.h
ln -s ../../Cellar/libtool/2.4.6_1/share/aclocal/libtool.m4 libtool.m4
ln -s ../../Cellar/libtool/2.4.6_1/share/aclocal/ltargz.m4 ltargz.m4
ln -s ../../Cellar/libtool/2.4.6_1/share/aclocal/ltdl.m4 ltdl.m4
ln -s ../../Cellar/libtool/2.4.6_1/share/aclocal/ltoptions.m4 ltoptions.m4
ln -s ../../Cellar/libtool/2.4.6_1/share/aclocal/ltsugar.m4 ltsugar.m4
ln -s ../../Cellar/libtool/2.4.6_1/share/aclocal/ltversion.m4 ltversion.m4
ln -s ../../Cellar/libtool/2.4.6_1/share/aclocal/lt~obsolete.m4 lt~obsolete.m4
ln -s ../../Cellar/libtool/2.4.6_1/share/info/libtool.info libtool.info
info /usr/local/share/info/libtool.info
ln -s ../../Cellar/libtool/2.4.6_1/share/info/libtool.info-1 libtool.info-1
ln -s ../../Cellar/libtool/2.4.6_1/share/info/libtool.info-2 libtool.info-2
ln -s ../Cellar/libtool/2.4.6_1/share/libtool libtool
ln -s ../../../Cellar/libtool/2.4.6_1/share/man/man1/glibtool.1 glibtool.1
ln -s ../../../Cellar/libtool/2.4.6_1/share/man/man1/glibtoolize.1 glibtoolize.1
ln -s ../Cellar/libtool/2.4.6_1/lib/libltdl.7.dylib libltdl.7.dylib
ln -s ../Cellar/libtool/2.4.6_1/lib/libltdl.a libltdl.a
ln -s ../Cellar/libtool/2.4.6_1/lib/libltdl.dylib libltdl.dylib
20 symlinks created

~
▶ go get go.mozilla.org/autograph

```

Note that I didn't use `-u` in that last `go get` so I guess it used my previous download of the files from go.mozilla.org.
